# Generated by Django 3.0.1 on 2020-05-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Email'),
        ),
    ]
