# Generated by Django 3.0.1 on 2020-01-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cover',
            field=models.ImageField(height_field=200, upload_to='img/', width_field=200),
        ),
    ]
