# Generated by Django 3.0.1 on 2020-05-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200505_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Username'),
        ),
    ]
