# Generated by Django 3.0.1 on 2020-05-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200522_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'permissions': (('view_draft', 'can see the drafts'), ('view_favorite', "can see the author's favorite articles"), ('view_save', "can see the author's saves")), 'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
    ]
