# Generated by Django 3.0.1 on 2020-06-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200522_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
    ]
