# Generated by Django 3.0.7 on 2020-06-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200603_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='media/images/default.png', null=True, upload_to='images/'),
        ),
    ]
