# Generated by Django 3.0.7 on 2020-06-26 02:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20190103_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('cook_time', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='must be greater than 0!')])),
                ('unit', models.CharField(blank=True, choices=[('s', 'seconds'), ('m', 'minutes'), ('h', 'hours')], default='m', max_length=5, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(help_text='Categorize this item.', to='category.Category')),
                ('favorites', models.ManyToManyField(related_name='post_favo', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(help_text='Tag this item.', to='category.Tag')),
            ],
            options={
                'ordering': ['-created_on'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('pic', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_steps', to='recipes.Post')),
            ],
            options={
                'verbose_name_plural': 'steps',
            },
        ),
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='must be greater than 0.01!')])),
                ('unit', models.CharField(blank=True, choices=[('g', 'gram'), ('mg', 'milligram'), ('kg', 'kilogram'), ('oz', 'Oz'), ('ml', 'milliliter'), ('l', 'liters'), ('c', 'cups'), ('table', 'tablespoon'), ('tea', 'teaspoon'), ('p', 'pound')], max_length=5, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ingredients', to='recipes.Post')),
            ],
            options={
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='recipes.Post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
