# Generated by Django 3.0.1 on 2020-04-27 00:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recipes.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('cook_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='must be greater than 1!')])),
                ('unit', models.CharField(blank=True, choices=[('s', 'seconds'), ('m', 'minutes'), ('h', 'hours')], default='m', max_length=5, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(choices=[('Flavors', ((11, 'spicy'), (12, 'sour'), (13, 'sweet'), (14, 'bitter'), (15, 'plain'))), ('Basic', ((21, 'breakfast'), (22, 'lunch'), (23, 'supper'), (24, 'snack'), (25, 'beverages'), (26, 'dessert'))), ('Style', ((31, 'foreign food'), (32, 'home cooking'), (33, 'local characteristics'))), ('People', ((41, 'Baby'), (42, 'Teenager'), (43, 'Old people'), (44, 'All'))), ('unknown', 'Unknown')], default='unknown', to='recipes.Category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Tea tea tea', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_steps', to='recipes.Post')),
            ],
            options={
                'verbose_name_plural': 'steps',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=1, help_text='eg: 2g', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='must be greater than 0.01!')])),
                ('unit', models.CharField(blank=True, choices=[('g', 'gram'), ('mg', 'milligram'), ('kg', 'kilogram'), ('oz', 'Oz'), ('ml', 'milliliter'), ('l', 'liters'), ('c', 'cups'), ('table', 'tablespoon'), ('tea', 'teaspoon'), ('p', 'pound')], max_length=5, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_ingredients', to='recipes.Post')),
            ],
            options={
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='recipes.Post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name'),
        ),
    ]
