# Generated by Django 3.0.1 on 2020-06-04 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200603_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='must be greater than 0!')]),
        ),
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.CharField(blank=True, choices=[('s', 'seconds'), ('m', 'minutes'), ('h', 'hours')], default='m', max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='CookTime',
        ),
    ]
