# Generated by Django 3.0.7 on 2020-06-20 00:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200604_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
