# Generated by Django 3.0.1 on 2020-03-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(choices=[('Beverages', ((11, 'Hot Beverage'), (12, 'Cold Beverage'))), ('Salad', ((21, 'Vegetable Salad'), (22, 'Fruit Salad'))), ('Normal', ((31, 'Breakfast'), (32, 'Lunch'), (33, 'Supper')))], default='No Type', to='recipes.Category'),
        ),
    ]
