# Generated by Django 3.0.1 on 2020-05-02 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20200427_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_save',
            field=models.ManyToManyField(related_name='post_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
