# Generated by Django 3.0.1 on 2020-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200424_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
