# Generated by Django 3.0.1 on 2020-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200324_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('', ''), ('g', 'gram'), ('mg', 'milligram'), ('kg', 'kilogram'), ('oz', 'Oz'), ('ml', 'milliliter'), ('l', 'liters'), ('c', 'cups'), ('table', 'tablespoon'), ('tea', 'teaspoon'), ('p', 'pound')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(choices=[('Basic', ((21, 'breakfast'), (22, 'lunch'), (23, 'supper'), (24, 'snack'), (25, 'beverages'), (26, 'dessert'))), ('Flavors', ((11, 'spicy'), (12, 'sour'), (13, 'sweet'), (14, 'bitter'), (15, 'plain'))), ('Style', ((31, 'foreign food'), (32, 'home cooking'), (33, 'local characteristics'))), ('People', ((41, 'Baby'), (42, 'Teenager'), (43, 'Old people'), (44, 'All'))), ('unknown', 'Unknown')], default='unknown', to='recipes.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cook_time',
            field=models.IntegerField(blank=True, choices=[('s', 'second'), ('m', 'min'), ('h', 'hr')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, max_length=1),
        ),
    ]
