# Generated by Django 3.0.1 on 2020-03-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200315_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_status',
        ),
    ]
