# Generated by Django 3.0.1 on 2020-04-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200425_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Tea tea tea', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='step',
            name='pic',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
