# Generated by Django 3.0.1 on 2020-05-02 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_post_my_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='my_save',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
