# Generated by Django 3.0.1 on 2020-03-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200324_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='description', max_length=300)),
                ('pic', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_steps', to='recipes.Post')),
            ],
            options={
                'verbose_name_plural': 'steps',
            },
        ),
    ]
