# Generated by Django 3.0.1 on 2020-05-03 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20200502_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_save',
        ),
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='post_favo', to=settings.AUTH_USER_MODEL),
        ),
    ]
