# Generated by Django 3.0.7 on 2020-07-03 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200703_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=52, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=52, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_cat', to='recipes.Category'),
        ),
    ]
