# Generated by Django 3.0.1 on 2020-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200328_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='pic',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
