# Generated by Django 3.0.1 on 2020-05-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200507_2221'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together={('id', 'slug')},
        ),
    ]
