# Generated by Django 3.0.1 on 2020-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200329_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'gram'), ('mg', 'milligram'), ('kg', 'kilogram'), ('oz', 'Oz'), ('ml', 'milliliter'), ('l', 'liters'), ('c', 'cups'), ('table', 'tablespoon'), ('tea', 'teaspoon'), ('p', 'pound')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(choices=[('Flavors', ((11, 'spicy'), (12, 'sour'), (13, 'sweet'), (14, 'bitter'), (15, 'plain'))), ('Basic', ((21, 'breakfast'), (22, 'lunch'), (23, 'supper'), (24, 'snack'), (25, 'beverages'), (26, 'dessert'))), ('Style', ((31, 'foreign food'), (32, 'home cooking'), (33, 'local characteristics'))), ('People', ((41, 'Baby'), (42, 'Teenager'), (43, 'Old people'), (44, 'All'))), ('unknown', 'Unknown')], default='unknown', to='recipes.Category'),
        ),
    ]
