# Generated by Django 3.0.1 on 2020-05-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20200507_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecount',
            name='like_num',
        ),
    ]
