# Generated by Django 3.0.1 on 2020-03-29 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20200329_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='eg: 2g', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='must be greater than 0!')]),
        ),
    ]
