# Generated by Django 3.0.1 on 2020-05-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200509_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
