# Generated by Django 3.0.1 on 2020-04-09 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20200407_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.CharField(blank=True, choices=[('s', 'second'), ('m', 'minutes'), ('h', 'hours')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='must be greater than 1!')]),
        ),
    ]
